### PR TITLE
Enable TLS option to serve API

### PR DESCRIPTION
**Pull request by fredbi**
* refactor help messages

Signed-off-by: Frederic BIDON <frederic@oneconcern.com>

### CODE REVIEW

**Comment by fredbi** [comment]
Some refactoring has been carried out. Next I believe, some parts now identical might be factorized in the common package.

**Comment by fredbi** [comment]
Note: the interface for metrics-middleware has changed while writing this PR. Padded missing args (sampling, endpoint) with some default values. I am really not sure about those. Please advise.

**Comment by aeneasr** [comment]
As long as metrics-middleware isn't bumped in version this is fine!

**Comment by aeneasr** [comment]
Thanks :)

**Pull request merged**
