### PR TITLE
WIP: Tests: Add Context Conditon Tests for EqualsSubjectCondition and StringEqualCondition

### PR DESCRIPTION
**Pull request by ppvolto**
## Related issue
Context Condition based Tests for #82 
Contains some Tests for EqualsSubjectCondition and some for StringEqualCondition

## Checklist

- [x] I have read the [contributing guidelines](CONTRIBUTING.md)
- [x] I confirm that this pull request does not address a security vulnerability. If this pull request addresses a security
vulnerability, I confirm that I got green light (please contact [hi@ory.sh](mailto:hi@ory.sh)) from the maintainers to push the changes.
- [x] I signed the [Developer's Certificate of Origin](https://github.com/ory/keto/blob/master/CONTRIBUTING.md#developers-certificate-of-origin)
by signing my commit(s). You can amend your signature to the most recent commit by using `git commit --amend -s`. If you
amend the commit, you might need to force push using `git push --force HEAD:<branch>`. Please be very careful when using
force push.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation within the code base (if appropriate)
- [ ] I have documented my changes in the [developer guide](https://github.com/ory/docs) (if appropriate)

### CODE REVIEW

**Comment by aeneasr** [comment]
Thank you for this! I'll look into this next week.

**Comment by ppvolto** [comment]
Sorry for the late Reply. I have updated Yesterday afternoon the Tests for the Fixed API call in master.

**Comment by aeneasr** [comment]
Sorry, I dropped the ball on this. The tests do not make a lot of sense because context and conditions are reversed. [This](https://github.com/ory/keto/pull/83/files#diff-4e9a0f04892063b0527c86aac15138c6R230) should be part of the policy, while [this](https://github.com/ory/keto/pull/83/files#diff-4e9a0f04892063b0527c86aac15138c6R399) should be part of the request. The policy says under which condition (e.g. the subject has to match something) the policy matches. The request says what the context is (e.g. the subject is peter).

**Comment by ppvolto** [comment]
Thanks for the description of the Errors in my Tests.
Now that i had a better look i understand the Error i had in the Tests itself.
And hopefully i understand the Tests in this and other Projects better in the future a little Better.

**Comment by aeneasr** [comment]
Don't worry about it - thank you for your time and effort you took for contributing to this project :)

**Pull request closed without merging**
