### PR TITLE
Fix typo in README

### PR DESCRIPTION
**Pull request by benjie**
Single character fix; sorry for not following protocol of reviewing the contributing guidelines/etc!

### CODE REVIEW

**Comment by benjie** [comment]
I honestly don't think this can fall under copyright so don't think there's any need to sign the CLA. Feel free to close and implement the fix yourself :grin:

**Comment by vinckr** [comment]
Hello @benjie 

That is true, but we can't merge this without the CLA check passing unfortunately. 
As a small perk you would get Ory Swag as a gift for your first contribution :-).

If that does not convince you, feel free to close this PR and I will fix it, 

Thanks

**Comment by benjie** [comment]
SOLD!

**Review by zepatrik — APPROVED** [review]

**Comment by vinckr** [comment]
Congrats on merging your first PR in Ory @benjie  🎉 !
Your contribution will soon be helping secure millions of identities around the globe 😁  
As a small token of appreciation we send all our first time contributors a gift package to welcome them to the community. 
[Please drop me an email and I will forward you the form to claim your Ory swag!](mailto:vincent@ory.sh)

**Pull request merged**
