### PR TITLE
chore: contextualize everything

### PR DESCRIPTION
**Pull request by zepatrik**

### CODE REVIEW

**Comment by aeneasr** [comment]
Bruh that was fast

**Review by aeneasr — COMMENTED** [review]
LGTM

Did you do a search for `context.Background()` / `context.TODO()` across the repo to make sure it's not used in any non-test code?

**Review by zepatrik — COMMENTED** [review]
> Did you do a search for context.Background() / context.TODO() across the repo to make sure it's not used in any non-test code?

Yes :heavy_check_mark: 

> Can you confirm that r.c is not used anywhere else?

Yes :heavy_check_mark:

**Comment by aeneasr** [comment]
congrats! 🎉

**Pull request merged**
