### PR TITLE
docs: allow $schema key in config.schema.json

### PR DESCRIPTION
**Pull request by dbtek**
Fixes json schema validation to allow $schema key which provides ide support.

## Related issue(s)

#1082

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
- [x] I have referenced an issue containing the design document if my change
      introduces a new feature.
- [x] I am following the
      [contributing code guidelines](../blob/master/CONTRIBUTING.md#contributing-code).
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security vulnerability, I
      confirm that I got the approval (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [ ] I have added tests that prove my fix is effective or that my feature
      works.
- [ ] I have added or changed [the documentation](https://github.com/ory/docs).

### CODE REVIEW

**Review by zepatrik — CHANGES_REQUESTED** [review]
Awesome :+1: 
The only problem is that this file is auto-generated from https://github.com/ory/keto/blob/642f674f99da3315d6c8b310f71b7a6999af785f/embedx/config.schema.json so you have to add it there as well to make this change persistent.

**Review by zepatrik — APPROVED** [review]
I quickly transferred the changes there.

**Comment by dbtek** [comment]
Thanks @zepatrik. Sorry I couldn't reply in time.

**Comment by vinckr** [comment]
Hello @dbtek 
Congrats on merging your first PR in Ory 🎉 !
Your contribution will soon be helping secure millions of identities around the globe 🌏. 
As a small token of appreciation we send all our first time contributors a gift package to welcome them to the community. 
[Please drop me an email and I will forward you the form to claim your Ory swag!](mailto:vincent@ory.sh)

**Pull request merged**
