### PR TITLE
feat: dockerfile and docker compose example

### PR DESCRIPTION
**Pull request by zepatrik**
Update Dockerfile to actually work againt.
Also added a small example that can be started using docker-compose.

### CODE REVIEW

**Comment by zepatrik** [comment]
@tacurran is there something left you want to look into? Did you get it up and running?

**Comment by tacurran** [comment]
@patrick. I still need until EOD to finish some stuff.  Nice work here. !

**Comment by aeneasr** [comment]
@tacurran what's the status? We want to finish this up and will merge it as is EOD.

**Comment by tacurran** [comment]
@aeneasr I will be done my review and changes by EOD 18:00

**Review by tacurran — APPROVED** [review]

**Pull request merged**
